---
name: "main"

on:
  workflow_call:
    inputs:
      DEV_CICD_DEBUG:
        description: "Enable debug mode"
        default: "NONE"
        required: false
        type: "string"

permissions:
  contents: read

env:
  BL64_LIB_CICD: "YES"
  DEV_TEST_BASH_RUNNER_ENVIRONMENT: "ON"
  DEV_CICD_DEBUG: "${{ inputs.DEV_CICD_DEBUG }}"
  MY_REPORT_PATH: "./logs/gitleaks/gitleaks.sarif"

jobs:
  sast-gitleaks:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Check pre-requisites"
        run: |
          test -f ./bin/dev-set || { echo "::error title=dependency-check::DevBin64 is not available in the target repository" && exit 1; }
          test -f ./bin/dev-lib-gitleaks || { echo "::error title=dependency-check::GitLeaks module not installed in the target repository" && exit 1; }

      - name: "Cache local tools"
        uses: "actions/cache@v5"
        with:
          path: \
            ./lib/bl64
            ./lib/inst64
          key: "lib-base"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-lib-gitleaks

      - name: "Run SAST"
        run: "./bin/dev-sast-gitleaks"

      - name: "Upload report to CodeQL"
        uses: "github/codeql-action/upload-sarif@v4"
        if: always()
        with:
          sarif_file: "${{ env.MY_REPORT_PATH }}"
          category: "secrets"

      - name: "Save report artifact"
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: "gitleaks.sarif"
          path: "${{ env.MY_REPORT_PATH }}"
...
